name: Deploy to Azure Storage

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu VM

    steps:
    - uses: actions/checkout@v2
      # Checks out your repository under $GITHUB_WORKSPACE, so the job can access it

    # Uncomment and modify the following lines if your project needs a build step
    # - name: Build
    #   run: <your build command>

    - name: Upload to Azure Blob Storage
      uses: cedric05/upload-to-azure-blob-storage@v1
      with:
        # Specify the directory to upload. Here, './web' implies that there's a folder named 'web' in your repository.
        source-file: './web'  
        
        # base-project-path is usually the directory in the source repository that should be treated as the root. 
        # If the entire repository is to be uploaded, this can be set to './'
        base-project-path: './'  
        
        # target-file is the path in the Azure Blob Storage where files will be uploaded.
        # '/' denotes the root of the container. Change this if you want to upload to a specific directory inside the container.
        target-file: '/'  
        
        # Set to 'true' to overwrite existing files in the blob storage
        overwrite: 'true'  
        
        # The name of the Azure Blob Storage container
        container-name: '$web'  
        
        # Azure Storage Account name, set this in your repository's secrets
        storage-account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} 
        
        # Azure credentials, set this in your repository's secrets
        creds: ${{ secrets.AZURE_CREDENTIALS }}
