name: Deploy to Azure Storage

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Add steps for building your site here if necessary
    # - name: Build
    #   run: <your build command>

    - name: Upload to Azure Blob Storage
  # You may pin to the exact commit or the version.
  # uses: cedric05/upload-to-azure-blob-storage@e290ac0044cbcd61f13a1e28d00b595904238b63
      uses: cedric05/upload-to-azure-blob-storage@v1
      with:
        # source file to upload
        source-file: './web'
        # base path to stack up
        base-project-path: ''
        # target path in azure blob storage container
        target-file: '/'
        # overwrite if target-dir exists
        overwrite: 'true' # optional
        # azure blob storage container name
        container-name: '$web'
        # azure storage account name
        storage-account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        # az create-rb output
        creds: ${{ secrets.AZURE_CREDENTIALS }}
              
